### ISSUE TITLE
Escrever o documento de Prototipação

### ISSUE THREAD

**Issue by durvalcarvalho** [Requisitos-de-Software/2020.2-PlantJammer#31]
### Descrição

A partir dos artefatos coletados, se houver a necessidade de implementação de uma nova funcionalidade, será criado um documento de descrição e prototipação.  

### Tasks

- [ ] Justificativa da prototipagem
- [ ] Estimar funcionalidades que devem ser prototipadas
- [ ] Comentar novas tasks ou fechar issue a partir da decisão feita pelo grupo
