### ISSUE TITLE
Criar documento do Storyboard

### ISSUE THREAD

**Issue by durvalcarvalho** [Requisitos-de-Software/2020.2-PlantJammer#33]
### Descrição

O storyboard é um documento que detalha uma narrativa de caso de uso da aplicação. Essa issue contempla a criação do artefato e sobre as conclusões sobre o mesmo.

### Tasks

- [x] Elaborar história/caso de uso para o storyboard
- [x] Criar os quadrinhos do storyboard
- [x] Criar documentação

### Critério de aceitação

- [ ] O documento deve está na wiki
